# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c962064b9edd56cbe876e6be69c87d9449ad9bf21c91637dfff2993a667964014554c09b1518dc963470d8d817f02a63207da16eefaea0459d6e3a560ce47d4

test:
  secret_key_base: ef37313a4619de0e15bb269d88f1aab763b8b9911c8651b63089cf3e38cf293a1a4f29f90df9712e285f74f445d9e648b1bdb6ce14d8f561ef743b038cb37e41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
